/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

'use strict';

var obsidian = require('obsidian');

/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */

function __awaiter(thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
}

const DEFAULT_SETTINGS = {
    languages: { "e3dea0f5-37f2-4d79-ae58-490af3228069": "js" },
};
class CodeBlockFromSelection extends obsidian.Plugin {
    onload() {
        return __awaiter(this, void 0, void 0, function* () {
            yield this.loadSettings();
            this.initCommands();
            this.addSettingTab(new SettingTab(this.app, this));
        });
    }
    initCommands() {
        for (const [uuid, language] of Object.entries(this.settings.languages)) {
            this.addCommand({
                id: uuid,
                name: language,
                callback: () => this.insertCodeBlock(language),
            });
        }
    }
    _addCommand(id, language) {
        this.addCommand({
            id: id,
            name: language,
            callback: () => this.insertCodeBlock(language),
        });
    }
    uuid() {
        var d = Date.now();
        if (typeof performance !== "undefined" &&
            typeof performance.now === "function") {
            d += performance.now(); //use high-precision timer if available
        }
        return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function (c) {
            var r = (d + Math.random() * 16) % 16 | 0;
            d = Math.floor(d / 16);
            return (c === "x" ? r : (r & 0x3) | 0x8).toString(16);
        });
    }
    insertCodeBlock(language) {
        let editor = this.getEditor();
        if (editor) {
            let selectedText = this.getSelectedText(editor);
            let line = this.getLineUnderCursor(editor).start.line;
            editor.replaceSelection(`\`\`\`${language}\n${selectedText}\n\`\`\`\n`);
            if (!selectedText) {
                editor.setSelection({ line: line + 1, ch: 0 });
            }
        }
    }
    getEditor() {
        var _a;
        return (_a = this.app.workspace.getActiveViewOfType(obsidian.MarkdownView)) === null || _a === void 0 ? void 0 : _a.sourceMode.cmEditor;
    }
    getSelectedText(editor) {
        if (!editor.somethingSelected())
            this.selectLineUnderCursor(editor);
        return editor.getSelection();
    }
    selectLineUnderCursor(editor) {
        let selection = this.getLineUnderCursor(editor);
        editor.getDoc().setSelection(selection.start, selection.end);
    }
    getLineUnderCursor(editor) {
        let fromCh, toCh;
        let cursor = editor.getCursor();
        fromCh = 0;
        toCh = editor.getLine(cursor.line).length;
        return {
            start: { line: cursor.line, ch: fromCh },
            end: { line: cursor.line, ch: toCh },
        };
    }
    loadSettings() {
        return __awaiter(this, void 0, void 0, function* () {
            this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
        });
    }
    saveSettings() {
        return __awaiter(this, void 0, void 0, function* () {
            yield this.saveData(this.settings);
        });
    }
}
class SettingTab extends obsidian.PluginSettingTab {
    constructor(app, plugin) {
        super(app, plugin);
        this.plugin = plugin;
    }
    display() {
        let { containerEl } = this;
        containerEl.empty();
        containerEl.createEl("h2", {
            text: "Code block from selection - Settings",
        });
        new obsidian.Setting(containerEl).setName("Add new language").addButton(cb => {
            cb.setButtonText("Add");
            cb.setCta();
            cb.onClick(() => {
                this.addNewLanguage();
            });
        });
        // init settingtab
        for (const [uuid, language] of Object.entries(this.plugin.settings.languages)) {
            const setting = new obsidian.Setting(containerEl);
            setting
                .setName("Language")
                .setDesc("")
                .addText(text => text
                .setPlaceholder("add new language")
                .setValue(language)
                .onChange((value) => __awaiter(this, void 0, void 0, function* () {
                this.plugin.settings.languages[uuid] = value;
                yield this.plugin.saveSettings();
                this.plugin._addCommand(uuid, value);
            })));
            this.addExtraButton(setting, uuid);
        }
    }
    addNewLanguage() {
        let setting = new obsidian.Setting(this.containerEl);
        let uuid = this.plugin.uuid();
        setting
            .setName("language")
            .setDesc("")
            .addText(text => text.setPlaceholder("add new language").onChange((value) => __awaiter(this, void 0, void 0, function* () {
            this.plugin.settings.languages[uuid] = value;
            yield this.plugin.saveSettings();
            this.plugin._addCommand(uuid, value);
        })));
        this.addExtraButton(setting, uuid);
    }
    addExtraButton(setting, uuid) {
        setting.addExtraButton(cb => {
            cb.setIcon("cross");
            cb.setTooltip("Remove");
            cb.onClick(() => {
                delete this.plugin.settings.languages[uuid];
                this.plugin.saveSettings();
                this.plugin.app.commands.removeCommand(`${this.plugin.manifest.id}:${uuid}`);
                setting.settingEl.hide();
            });
        });
    }
}

module.exports = CodeBlockFromSelection;


/* nosourcemap */